### ISSUE TITLE
Brief Question About Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [shanedonovan/U4VRESTClient#1]
Dear developer,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., sun.misc.Unsafe). Your feedback will help to guide our research.

1. You used an internal interface in `RESTClient` class of your project. Did you know that it is an internal interface of the Java library?
2. Are you aware that internal interfaces are unstable and may change without backward-compatibility?

Interface:  `sun.misc.BASE64Encoder`
File: [RESTClient.java](https://github.com/shanedonovan/U4VRESTClient/blob/a9cd5b34747c273c70d4e6c4a5b4e9857fee1c89/src/main/java/com/github/shanedonovan/rest/client/RESTClient.java)
Line: 17

**Comment by shanedonovan** [comment]
Hi alinebrito

Thanks for pointing this out to me, I was unaware of how unstable internal interfaces were. From looking into this I have noticed that Oracle have released a Base64 encoder/decoder in the java.util package, so I am now using that instead.

Thanks,
Shane

**Comment by alinebrito** [comment]
Hi @shanedonovan 

Thanks for your feedback! It is very useful for my research.
